Feature/goerli crosschain
iExecBlockchainComputing/generic-oracle-dapp pull request #13
Opened 2022-06-14 15:00 UTC by jeremyjams

2022-06-15 14:44 UTC, PierreJeanjacquot requested changes
Before anything else, format and lint the code to track most of the common issues.
Once done see the comments.

## prettier / estlint config for TS
install deps
```
npm i --save-dev eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin prettier eslint-config-prettier eslint-plugin-prettier
```

`.eslintrc`
```
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2020,
    "sourceType": "module"
  },
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended"
  ],
  "rules": {}
}
```

2022-06-15 14:44 UTC, PierreJeanjacquot commented on package-lock.json
> +  "lockfileVersion": 2,
lockfile version upgraded (incompatible with npm < 7)

2022-06-16 15:31 UTC, jeremyjams commented on package.json
>    "devDependencies": {
Is it better now?

2022-06-21 14:24 UTC, PierreJeanjacquot commented on tests/contractLoader.test.ts
> +import { expect } from "chai";
remove `chai` from dependencies

2022-06-21 15:13 UTC, jeremyjams commented on tests/contractLoader.test.ts
> +import { expect } from "chai";
Updated thanks https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/13/commits/128faa07668ba7936ec56381e6b34cc00ca7b8af.

2022-06-24 07:27 UTC, jeremyjams commented on package.json
> +    "@jeremyjames/generic-oracle-contracts": "^1.1.0-0",
Updated here https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/13/commits/b3b7e2320a1e2b1c2e7c5df705fd68051f1065e9, thanks :)

2022-06-27 14:10 UTC, PierreJeanjacquot requested changes
some more minor adjustments

2022-06-28 14:06 UTC, jeremyjams commented on src/contractLoader.ts
> +    const appDeveloperSecretsJsonString = buff.toString("utf-8");
OK, thanks!

2022-06-28 15:12 UTC, jeremyjams commented on src/dapp.ts
> +  const encodedValue: string | undefined = encodeValue(
Thanks for your NB, I see :+1: (https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/13/commits/8b15022c970067030df97c8e171202d26ce3175c)

2022-06-28 15:24 UTC, jeremyjams commented on src/contractLoader.ts
> +    const appDeveloperSecretJson: OracleArgs = JSON.parse(
Added explicit control, thanks (https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/13/commits/b18072137918445b64aa26514636f987aec6ecc2)

2022-06-30 08:32 UTC, jeremyjams commented on src/contractLoader.ts
> +export class OracleArgs {
Ok, at least updated to an interface (https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/13/commits/adac22a8a1eb4fff6a64140f52d0d1b5bb054e25)

2022-06-30 08:33 UTC, jeremyjams commented on src/dapp.ts
> +    if (receipt.blockNumber) {
Thank you, updated here: https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/13/commits/07ef14a4e59530787a1a5f48447fd5af54ba56e2

2022-07-01 09:01 UTC, PierreJeanjacquot approved these changes

2022-07-01 12:49 UTC, merged