Feature/metatxs to forwarder api
iExecBlockchainComputing/generic-oracle-dapp pull request #17
Opened 2022-11-02 16:51 UTC by jeremyjams

2022-11-04 13:18 UTC, PierreJeanjacquot requested changes

2022-11-07 15:54 UTC, jeremyjams commented on src/dapp.ts
> +        Array.from(new Set(process.argv[2].split(",").sort()), Number)
Thanks updated here https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/17/commits/182ae80388612268b40f55e2a06f44f102363762

2022-11-07 15:54 UTC, jeremyjams commented on src/forward/forwardHandler.ts
> +  );
Thanks, see https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/17/commits/182ae80388612268b40f55e2a06f44f102363762

2022-11-08 08:39 UTC, jeremyjams commented on src/validators.js
> +    .transform((value, originalValue) => Array.from(new Set(originalValue.split(',').sort())))
Thank you for the notice! Sorting here is not purely required but helps to keep up with flow if digging in logs later. Here is the new sorting https://github.com/iExecBlockchainComputing/generic-oracle-dapp/pull/17/commits/7fc1f6b134bd0544e636b6de639dc877d29e6329.

2022-11-08 10:10 UTC, PierreJeanjacquot approved these changes

2022-11-08 16:03 UTC, merged