add sepolia & amoy network config
iExecBlockchainComputing/generic-oracle-dapp pull request #34
Opened 2024-11-25 15:44 UTC by abbesBenayache

2024-11-26 09:10 UTC, PierreJeanjacquot requested changes
The version of ethers currently used does not provide fallback providers for networks 11155111 (Sepolia) and 80002 (Amoy)

2024-11-26 09:10 UTC, PierreJeanjacquot commented on config.dev.json
>        "providerUrl": ""
```
generic-oracle-dapp@2.1.1
└── ethers@5.6.8 
```
The version of ethers currently used does not provide fallback providers for networks 11155111 (Sepolia) and 80002 (Amoy)
While Sepolia was added in the latest `ethers@5` (5.7.2), Amoy was not, we still need to specify the `providerUrl`

TODO:
- update ethers dependency to the latest v5 `npm i ethers@5` (do not attempt to upgrade to `ethers@6` which cannot run in node 14.4.0)
- add `providerUrl` config for network `80002`

2024-11-26 11:07 UTC, abbesBenayache commented on config.dev.json
>        "providerUrl": ""
commit : 996c96582550f7126ec95ff0631a398a517c967a

commit : a6305a464f2aff03ebac6e97f3f275136ed4f090

2024-11-27 09:16 UTC, PierreJeanjacquot approved these changes
LGTM

2024-11-27 09:27 UTC, merged